rmarkdown::render("./implementationValidation.R", output_dir = "../reports")
rmarkdown::render("./rawDataMeta.R", output_dir = "../reports")
rmarkdown::render("./simpleIntervals.R", output_dir = "../reports")
rmarkdown::render("./simpleIntervalsLM.R", output_dir = "../reports")
rmarkdown::render("./groupNlmeDiag.R", output_dir = "../reports")
rmarkdown::render("./groupNlmeMitoplasts.R", output_dir = "../reports")
rmarkdown::render("./groupNlmeMito.R", output_dir = "../reports")
rmarkdown::render("./explanationFigure.R", output_dir = "../reports")
rmarkdown::render("./representativeFigure.R", output_dir = "../reports")
rmarkdown::render("./mainArgument.Rmd", output_dir = "../reports/article")
knitr::knit("./supplementaryMaterials.Rnw", output = "./supplementaryMaterials.tex")
system("pdflatex -output-directory=../reports/article supplementaryMaterials.tex")
# Do it a second time for references
system("pdflatex -output-directory=../reports/article supplementaryMaterials.tex")
